export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';
export const PERMISSION_GROUP_REPOSITORY = 'PERMISSION_GROUP_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
